DATA:
    ROOT: '../../Datasets/'
    TRAIN_FILE: '../../Datasets/list/kinetics_train.txt'
    VAL_FILE: '../../Datasets/list/kinetics_val.txt'
    DATASET: kinetics-400
    NUM_FRAMES: 8
    NUM_CLASSES: 400
    LABEL_LIST: 'labels/kinetics_400_labels.csv'
MODEL:
    ARCH: ViT-B/16
    RESUME: '/home/ps/userfile/zhengzhenxing/VideoX-clip/X-CLIP/exp/ViT-B/32/2023-01-18-20-00-29/best.pth'
    PRETRAINED: None
TRAIN:
    BATCH_SIZE: 64
    ACCUMULATION_STEPS: 4
    EPOCHS: 30
    LR: 8.e-6
TEST:
    NUM_CLIP: 1
    NUM_CROP: 1
    ONLY_TEST: True
    BATCH_SIZE: 8
OUTPUT: 'exp'