DATA:
    ROOT: '../../Datasets/'
    TRAIN_FILE: '../../Datasets/list/sthv2_train.txt' # sthv2_train
    VAL_FILE: '../../Datasets/list/sthv2_val.txt' # sthv2_val
    DATASET: 'sthv2'
    NUM_FRAMES: 8
    NUM_CLASSES: 174
    LABEL_LIST: 'labels/sthv2_labels.csv' # sthv2_labels_zzx
MODEL:
    ARCH: ViT-B/16
    RESUME: None
    PRETRAINED: None
TRAIN:
    BATCH_SIZE: 32
    ACCUMULATION_STEPS: 8
    EPOCHS: 30
    LR: 8.e-6
TEST:
    NUM_CLIP: 1
    NUM_CROP: 1
    ONLY_TEST: False
    BATCH_SIZE: 8
OUTPUT: 'exp'