DATA:
    ROOT: '../../Datasets/'
    TRAIN_FILE: '../../Datasets/list/ucf_split1_train.txt'
    VAL_FILE: '../../Datasets/list/ucf_split1_test.txt'
    DATASET: ucf101
    NUM_FRAMES: 16
    NUM_CLASSES: 101
    LABEL_LIST: 'labels/ucf_101_labels_blank.csv'
MODEL:
    ARCH: ViT-B/16
    RESUME: '/home/ps/userfile/zhengzhenxing/VideoX-clip/X-CLIP/exp/k400/ViT-B/16/2023-01-27-14-50-46/best.pth'
    PRETRAINED: None
TRAIN:
    BATCH_SIZE: 4
    ACCUMULATION_STEPS: 2
    EPOCHS: 50
    LR: 2.e-6
TEST:
    NUM_CLIP: 4
    NUM_CROP: 3
    ONLY_TEST: True
    BATCH_SIZE: 8
OUTPUT: 'exp'