DATA:
    ROOT: '/PATH/TO/videos'
    TRAIN_FILE: '/PATH/TO/train.txt'
    VAL_FILE: '/PATH/TO/val.txt'
    DATASET: kinetics600
    NUM_FRAMES: 8
    NUM_CLASSES: 600
    LABEL_LIST: 'labels/kinetics_600_labels.csv'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 8
    ACCUMULATION_STEPS: 4